DATA:
  dataset: "FashionMNIST"
  image_size: 32
  categorical: False
  val_categorical: True
  normalize: True
  horizontal_flip: True
  padding: True
  merge_train_val: True
  drop_remainder: True
OPTIMIZATION:
  optimizer: "adam"
  g_lr: 0.0002 # 2e-4
  g_beta1: 0.5
  g_beta2: 0.999
  d_lr: 0.0002 # 2e-4
  d_beta1: 0.5
  d_beta2: 0.999
  adam_eps: 0.000001 # 1e-6
  g_updates_per_step: 1
  d_updates_per_step: 3
  split_batch_d_steps: False
  acml_steps: 1
  random_labels: False
  batch_size: 64
  val_batch_size: 128
  epochs: 300
  save_optimizer: True
MODEL:
  name: "biggan_deep"
  studiogan: True
  hier: True
  latent_dim: 128
  shared_dim: 128
  g_conv_dim: 128
  g_depth: 2
  apply_g_attn: True
  d_conv_dim: 128
  d_depth: 2
  apply_d_attn: True
  d_wide: True
  blur_resample: False
  residual_concat: False
  apply_g_ema: True
  g_ema_decay: 0.9999
  g_ema_start: 1000
LOSS:
  type: 'hinge'
  grad_penalty_type: null
CLS_PRE:
  name: "resnet20"
  optimizer: "sgdw"
  random_erasing: True
  extra_name: ''
RUN:
  seed: 42
  save: True
  extra_name: ''
  mixed_precision: False
  compute_metrics: False
  start_eval_epoch: 0
  compute_classifier_stats: False
  reload: False
  show_plots: False
  plot_with_title: True
  plot_title: ''
  keep_images: False
  fixed_seed: True
